---
title: "Study 1 Results Model"
author: "Spike Huang"
date: "2025-04-25"
output:
  cleanrmd::html_document_clean:
    theme: marx
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  highlight = TRUE
)
```

## Packages
```{r, message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)
library(stringr)
library(lme4)
library(lmerTest)
library(car)
library(effectsize)
library(emmeans)
library(performance)
library(report)
library(ggplot2)
```

## Load Data
```{r, message=FALSE, warning=FALSE}
df <- read_excel("data/Study_1_Subjective_Data.xlsx")
head(df)
```

## Recode Core Variables
```{r, message=FALSE, warning=FALSE}
df <- df %>%
  mutate(
    Model = factor(Model),
    Profession = factor(Profession),
    Task = factor(Task),
    Iteration = factor(Iteration),
    ID = factor(ID),
    RaterGroup = Profession,
    Attempt = Iteration,
    Rater = factor(paste(RaterGroup, ID, sep = "_")),
    OverallQuality = rowMeans(
      across(
        c(
          Statistical_Accuracy,
          Clarity_and_Structure,
          Conceptual_Depth,
          Pedagogical_Effectiveness
        )
      ),
      na.rm = TRUE
    ),
    ModelGroup = case_when(
      str_detect(Model, regex("ChatGPT_4o", ignore_case = TRUE)) ~ "Top",
      str_detect(Model, regex("ChatGPT_o1", ignore_case = TRUE)) ~ "Top",
      str_detect(Model, regex("Grok3", ignore_case = TRUE)) ~ "Bottom",
      str_detect(Model, regex("Gemini_2\\.0", ignore_case = TRUE)) ~ "Bottom",
      TRUE ~ "Other"
    ),
    ModelGroup = factor(ModelGroup, levels = c("Bottom", "Top", "Other"))
  )
```

## Filter Top and Bottom Models
``` {r, message=FALSE, warning=FALSE}
df_tb <- df %>%
  filter(ModelGroup %in% c("Top", "Bottom")) %>%
  droplevels()
```

## Fit Model
```{r, message=FALSE, warning=FALSE}
ggplot(df, aes(x = ModelGroup, y = OverallQuality)) +
  geom_point(aes(color = Rater)) +
  geom_smooth(method = "lm", se = FALSE, aes(group = Rater, color = Rater)) +
  facet_wrap(~Rater) +
  theme_minimal()
```

### Model1
```{r, message=FALSE, warning=FALSE}
# Model1 - With (1|Attempt)
model1 <- lmer(
  OverallQuality ~ ModelGroup * RaterGroup * Task +
    (1 | Rater) + (1 | Attempt),
  data = df
)

summary(model1)
```

### Model 2
```{r, message=FALSE, warning=FALSE}
# Model2 - Without (1|Attempt)
model2 <- lmer(
  OverallQuality ~ ModelGroup * RaterGroup +
    (1 | Rater),
  data = df
)

summary(model2)
```

### Model3
```{r, message=FALSE, warning=FALSE}
# Model3 - (ModelGroup|Rater)
model3 <- lmer(
  OverallQuality ~ ModelGroup * RaterGroup +
    (ModelGroup | Rater),
  data = df
)

summary(model3)
```

### Model4
```{r, message=FALSE, warning=FALSE}
# Model4 - (ModelGroup|Rater) + (1|Attempt)
model4 <- lmer(
  OverallQuality ~ ModelGroup * RaterGroup +
    (ModelGroup | Rater) + (1 | Attempt),
  data = df
)

summary(model4)
```

### Model Comparison
```{r, message=FALSE, warning=FALSE}
# Model comparison
compare_performance(model1, model2, model3, model4, rank = T)
```

### Model 1 Results
```{r, message=FALSE, warning=FALSE}
standardize_parameters(model1)
```

#### Type III ANOVA and Effect Sizes
```{r, message=FALSE, warning=FALSE}
aov_model1 <- anova(model1)
aov_model1
eta_squared(model1)
```

#### Post-hoc
```{r, message=FALSE, warning=FALSE}
emmeans(model1, pairwise ~ ModelGroup, infer = c(TRUE, TRUE))
emmip(model1, RaterGroup ~ ModelGroup, CIs = TRUE)
```

``` {r, message=FALSE, warning=FALSE}
emmeans(model1, pairwise ~ ModelGroup * RaterGroup, infer = c(TRUE, TRUE))
```

```{r, message=FALSE, warning=FALSE}
report(aov_model1)
```

#### Diagnostics
```{r, message=FALSE, warning=FALSE}
performance::check_model(model1)
performance::check_collinearity(model1)

res <- residuals(model1)
qqnorm(res)
qqline(res)
```
